FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY eureka-server/eureka-server/pom.xml .
COPY eureka-server/eureka-server/src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/eureka-server-1.0.0.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]