server.port=${PORT:8761}
spring.application.name=eureka-server

# Eureka Server ko khud register nahi karna apne aap mein
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Render pe apna URL daalo (deploy ke baad milega)
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.server.url=https://${RENDER_EXTERNAL_HOSTNAME:localhost}/eureka

# Logs
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
